#!/usr/bin/python
"""
    Simple message publisher 

    @author: Jean-Lou Dupont
"""
import os, sys, argparse
op=os.path

try:
    import jldzeromq
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldzeromq

########################################################################

DESC="PUBlish to topic"
DEFAULTS={
          }

def main():
    try:
        import jldzeromq.do_setup
        import logging
        import jldzeromq.do_checks
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@')
        
        parser.add_argument('-sp', dest='sock_pub',  type=str, help="Address for socket", required=True)
        parser.add_argument('-tp', dest='specified_topic',     type=str, help="Specify topic", default=None)  
             
        parser.add_argument('-js', dest='json_mode', action="store_true", help="JSON mode", default=False)
        
        parser.add_argument('-tf', dest='filter_topics', type=str, nargs='+', help="Topic(s) to filter out", default=[])
        
        args=parser.parse_args()
        
        from jldzeromq.tools_sys import dnorm, info_dump
        from jldzeromq.script_pub import run
        
        args=dnorm(vars(args))
        info_dump(args, 20)       
        run(**args)


    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())
