#!/usr/bin/env python
"""
    Simple Publish/Subscribe fabric
    
    @author: Jean-Lou Dupont
"""
import os, sys, argparse
op=os.path

try:
    import jldzeromq
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldzeromq

########################################################################

DESC="PUB/SUB fabric"
DEFAULTS={
          }

def main():
    try:
        import jldzeromq.do_setup
        import logging
        import jldzeromq.do_checks
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@')
        parser.add_argument('-ps', dest='sock_pub',  type=str, help="Socket for publishers", required=True)        
        parser.add_argument('-ss', dest='sock_sub',  type=str, help="Socket for subscribers", required=True)
        
        args=parser.parse_args()
        
        from jldzeromq.tools_sys import dnorm
        from jldzeromq.script_fabric import run
        run(**dnorm(vars(args)))

    except KeyboardInterrupt:
        logging.info("..Exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())
